```yaml
# Change these first
owner: azu # Your GitHub organization or username, where this repository lives
repo: npmcdn-upptime # The name of this repository

sites:
  # skypack
  - name: skypack.dev
    url: https://www.skypack.dev/
  - name: cdn.skypack.dev
    url: https://cdn.skypack.dev/canvas-confetti
  - name: status.skypack.dev
    url: https://status.skypack.dev/
  - name: "cdn.skypack.dev/{pkg}@{pin}"
    url: https://cdn.skypack.dev/preact@10.5.5
  - name: "cdn.skypack.dev/{pkg}@{major}"
    url: https://cdn.skypack.dev/preact@10
  - name: "cdn.skypack.dev/{pkg}@^{semver}"
    url: https://cdn.skypack.dev/preact@^10
  # unpkg
  - name: unpkg.com
    url: https://unpkg.com/
  - name: "unpkg.com/{pkg}"
    url: https://unpkg.com/preact
  - name: "unpkg.com/{pkg}@{pin}"
    url: https://unpkg.com/preact@10.5.5
  - name: "unpkg.com/{pkg}@{major}"
    url: https://unpkg.com/preact@10
  - name: "unpkg.com/{pkg}@^{semver}"
    url: https://unpkg.com/preact@^10
  # esm.sh
  - name: esm.sh
    url: https://esm.sh/
  - name: "esm.sh/{pkg}"
    url: https://esm.sh/preact
  - name: "esm.sh/{pkg}@{pin}"
    url: https://esm.sh/preact@10.5.5
  - name: "esm.sh/{pkg}@{major}"
    url: https://esm.sh/preact@10
  - name: "esm.sh/{pkg}@^{semver}"
    url: https://esm.sh/preact@^10



status-website:
  # cname: skypack.dev
  baseUrl: /npmcdn-upptime
  logoUrl: "https://user-images.githubusercontent.com/19714/225467596-013cbc1b-3a80-4d69-8fa1-27bf7e931b38.png"
  name: npmcdn-uptime
  introTitle: "Unofficial status page for npm package CDNs"
  introMessage: "This is un-official status page for <https://www.skypack.dev/>"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
```
